name: Run tests

on: [push, pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
     # Steps represent a sequence of tasks that will be executed as part of the job
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
